version: '3.8'

services:
  data-website:
    build: .
    restart: always
    # We remove volumes for production because the code is already inside the image
    # We remove ports because Dokploy/Traefik handles the web traffic for you
